# This file was generated by GoReleaser. DO NOT EDIT.
class Gh < Formula
  desc "GitHub CLI"
  homepage "https://github.com/cli/cli"
  version "0.5.3"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/cli/cli/releases/download/v0.5.3/gh_0.5.3_macOS_amd64.tar.gz"
    sha256 "9947b752d80a4fef723b868fa28f287a1d0f73638043c2e051d76cf104efeb1d"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/cli/cli/releases/download/v0.5.3/gh_0.5.3_linux_amd64.tar.gz"
      sha256 "23d19cd3e216904ea21b38768c25f5be56caf6f8713dffa378c07e9f088d1fbd"
    end
  end
  
  head do
    url "https://github.com/cli/cli.git"
    depends_on "go"
  end

  def install
    system "make" if build.head?
    bin.install "bin/gh"
    (bash_completion/"gh.sh").write `#{bin}/gh completion -s bash`
    (zsh_completion/"_gh").write `#{bin}/gh completion -s zsh`
    (fish_completion/"gh.fish").write `#{bin}/gh completion -s fish`
  end

  test do
    help_text = shell_output("#{bin}/gh --help")
    assert_includes help_text, "Usage:"
  end
end
