# This file was generated by GoReleaser. DO NOT EDIT.
class Gh < Formula
  desc "GitHub CLI"
  homepage "https://github.com/cli/cli"
  version "0.5.4"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/cli/cli/releases/download/v0.5.4/gh_0.5.4_macOS_amd64.tar.gz"
    sha256 "cfefffed92c9837360caf6678b11568c5a9ab4445d341f55f3630d5e5306c178"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/cli/cli/releases/download/v0.5.4/gh_0.5.4_linux_amd64.tar.gz"
      sha256 "b6725efd3b4ce8ea0d882c0b7519bd6122e950772b85528e8b84771a22880249"
    end
  end
  
  head do
    url "https://github.com/cli/cli.git"
    depends_on "go"
  end

  def install
    system "make" if build.head?
    bin.install "bin/gh"
    (bash_completion/"gh.sh").write `#{bin}/gh completion -s bash`
    (zsh_completion/"_gh").write `#{bin}/gh completion -s zsh`
    (fish_completion/"gh.fish").write `#{bin}/gh completion -s fish`
  end

  test do
    help_text = shell_output("#{bin}/gh --help")
    assert_includes help_text, "Usage:"
  end
end
