# This file was generated by GoReleaser. DO NOT EDIT.
class Gh < Formula
  desc "GitHub CLI"
  homepage "https://github.com/cli/cli"
  version "0.8.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/cli/cli/releases/download/v0.8.0/gh_0.8.0_macOS_amd64.tar.gz"
    sha256 "da388314df66f2c1763f5d6d94a1360ae3e71ce5e4077ce9f8919a385a457bc0"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/cli/cli/releases/download/v0.8.0/gh_0.8.0_linux_amd64.tar.gz"
      sha256 "7eb2633f8360239362726ac4265ef07a900bdc3f90d0f3dc36d7d03bce072d52"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cli/cli/releases/download/v0.8.0/gh_0.8.0_linux_arm64.tar.gz"
        sha256 "d5762a0c0e4a398d04f9126d0496275234b63e2ff304c274808e435ebdc0f0e7"
      else
      end
    end
  end
  
  head do
    url "https://github.com/cli/cli.git"
    depends_on "go"
  end

  def install
    system "make" if build.head?
    bin.install "bin/gh"
    (bash_completion/"gh.sh").write `#{bin}/gh completion -s bash`
    (zsh_completion/"_gh").write `#{bin}/gh completion -s zsh`
    (fish_completion/"gh.fish").write `#{bin}/gh completion -s fish`
  end

  test do
    help_text = shell_output("#{bin}/gh --help")
    assert_includes help_text, "Usage:"
  end
end
