# This file was generated by GoReleaser. DO NOT EDIT.
class Gh < Formula
  desc "GitHub CLI"
  homepage "https://github.com/cli/cli"
  version "0.6.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/cli/cli/releases/download/v0.6.1/gh_0.6.1_macOS_amd64.tar.gz"
    sha256 "a7ffd358476958541687da8108d7b2fc7adedbcb046ad7faa37ad4d7f381c314"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/cli/cli/releases/download/v0.6.1/gh_0.6.1_linux_amd64.tar.gz"
      sha256 "e2a3c1d6b0e514f3981cd812afde862ddc43b1be13ce6af5cd2843fff3c1606e"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cli/cli/releases/download/v0.6.1/gh_0.6.1_linux_arm64.tar.gz"
        sha256 "21916e6d335b28322886bc53f65addeca868ebd98fb7f8adeeb5fe74989a23cd"
      else
      end
    end
  end
  
  head do
    url "https://github.com/cli/cli.git"
    depends_on "go"
  end

  def install
    system "make" if build.head?
    bin.install "bin/gh"
    (bash_completion/"gh.sh").write `#{bin}/gh completion -s bash`
    (zsh_completion/"_gh").write `#{bin}/gh completion -s zsh`
    (fish_completion/"gh.fish").write `#{bin}/gh completion -s fish`
  end

  test do
    help_text = shell_output("#{bin}/gh --help")
    assert_includes help_text, "Usage:"
  end
end
